### PR TITLE
systemd service for starting/stopping amsterdam

### PR DESCRIPTION
**Pull request by Eagleman7**
Needs to go in:

/usr/lib/systemd/system/

start/stop/restart:
systemctl start amsterdam
systemctl stop amsterdam
systemctl restart amsterdam

start at boot:
systemctl enable amsterdam

### CODE REVIEW

**Comment by pevma** [comment]
Wondering if we can add "restart" too - might be useful?

**Comment by Eagleman7** [comment]
Restart is already included, all it does is ExecStop and then ExecStart

**Comment by pevma** [comment]
ok - just checking - thanks for the feedback!

**Comment by regit** [comment]
Merged after rebase.

**Pull request closed without merging**
