### PR TITLE
Changes to logstash command in docker-compose 

### PR DESCRIPTION
**Pull request by arr0n**
The change to the docker-compose means that logstash's configurations are held in the /etc/logstash/conf.d/ folder.  You can expand logstash by placing multiple configuration files in there.  It is inline with logstash's documentation.

### CODE REVIEW

**Comment by arr0n** [comment]
also, it may cause issues if you want to add in a pattern folder too.  They tend to live in /etc/logstash/patterns/ as well, which would all be fine if you still mount /etc/logstash/ and within that having a conf.d folder with configs.  Although i'm sure in the end it makes little difference

**Comment by regit** [comment]
That make sense. I'm gonna test you branch as it is and merge it if tests are succesfull.

**Comment by arr0n** [comment]
my only feedback on this is that it is a little heavy "as is" in the output given by logstash.  It might be worth setting logstash out to quite

**Comment by arr0n** [comment]
to be honest i'm very impressed by all the work done on this project, with a few configuration changes and some different mounts i was able to get nginx-reverse proxy (in a container) to out put its logs in logstash.

**Comment by regit** [comment]
Thanks @arr0n :) Blame docker team on flexibility ;)

**Comment by regit** [comment]
@arr0n regarding logstash verbosity, what kind of message do you have ? In my case, the noise is mostly caused by kibana.

**Comment by arr0n** [comment]
Basically everything logstash is handling is piping out into the
terminal.  I don't mind it, but it might be a little annoying for
others.  So in my case all the SELKS stuff and of course the nginx
reverse proxy stuff.

**Pull request merged**
